"use client";
import { useMemo, useState } from "react";
import { buyCall, buyQuote, sellCall, sellQuote, submitCall } from "@/lib/contract";
import { humanizeContractError } from "@/lib/errors";
import { formatStroops, parseTokenAmount } from "@/lib/utils";
import type { Market, Position } from "@/types/market";
import { Button, Card, Input } from "@/components/ui";
import { useWallet } from "@/providers/wallet-provider";

export function TradingPanel({ market, position, onComplete }: { market: Market; position: Position; onComplete: () => Promise<void> }) {
  const wallet = useWallet(); const [mode, setMode] = useState<"buy" | "sell">("buy"); const [side, setSide] = useState(true); const [amount, setAmount] = useState(""); const [status, setStatus] = useState("");
  const raw = parseTokenAmount(amount);
  const quote = useMemo(() => mode === "buy" ? buyQuote(market, raw, side) : sellQuote(market, raw, side), [market, mode, raw, side]);
  const output = mode === "buy" ? buyQuote(market, raw, side).shares : sellQuote(market, raw, side).payout;
  const closed = Date.now() / 1000 >= market.lockTime;
  async function execute() { if (!wallet.address) { setStatus("Connect a wallet to trade."); return; } if (!raw) { setStatus("Enter an amount first."); return; } setStatus("Preparing transaction…"); try { const minOut = mode === "buy" ? buyQuote(market, raw, side).minSharesOut : sellQuote(market, raw, side).minAmountOut; const call = mode === "buy" ? buyCall(market.id, wallet.address, side, raw, minOut) : sellCall(market.id, wallet.address, side, raw, minOut); await submitCall(wallet.address, call, wallet.signTransaction); setStatus("Confirmed. Refreshing market data…"); await onComplete(); setAmount(""); setStatus("Trade confirmed."); } catch (e) { setStatus(humanizeContractError(e)); } }
  if (closed) return <Card className="p-5"><h3 className="font-semibold">Trading is closed</h3><p className="mt-2 text-sm text-slate-400">This market passed its lock time. You can still claim resolved positions.</p></Card>;
  return <Card className="p-5"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-semibold">Trade market</h3><p className="mt-1 text-xs text-slate-500">Quotes include a 2% fee and 1.5% slippage protection.</p></div><div className="flex rounded-md border hairline p-1 text-xs"><button className={`rounded px-3 py-1.5 ${mode === "buy" ? "bg-blue-500 text-white" : "text-slate-400"}`} onClick={() => setMode("buy")}>Buy</button><button className={`rounded px-3 py-1.5 ${mode === "sell" ? "bg-blue-500 text-white" : "text-slate-400"}`} onClick={() => setMode("sell")}>Sell</button></div></div><div className="mb-4 flex gap-2">{[true, false].map((value) => <button key={String(value)} className={`flex-1 rounded-md border p-2 text-sm ${side === value ? "border-blue-400 bg-blue-500/10 text-blue-200" : "hairline text-slate-400"}`} onClick={() => setSide(value)}>{value ? "YES" : "NO"}{mode === "sell" && <span className="ml-2 text-xs text-slate-500">{formatStroops(value ? position.yes : position.no)} shares</span>}</button>)}</div><label className="mb-2 block text-xs uppercase tracking-wider text-slate-500">{mode === "buy" ? "Collateral amount" : "Shares to sell"}</label><Input value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="decimal" placeholder="0.00" /><div className="mt-4 rounded-md bg-slate-950/55 p-3 text-sm"><div className="flex justify-between text-slate-400"><span>Estimated output</span><span className="font-medium text-slate-100">{formatStroops(output)} {mode === "buy" ? "shares" : "USDC"}</span></div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>Effective price</span><span>{(Number(quote.effectiveBps) / 100).toFixed(2)}¢</span></div></div><Button className="mt-4 w-full" onClick={execute} disabled={status.includes("transaction") || status.includes("Refreshing")}>{mode === "buy" ? `Buy ${side ? "YES" : "NO"}` : `Sell ${side ? "YES" : "NO"}`}</Button>{status && <p className="mt-3 text-center text-xs text-slate-400">{status}</p>}</Card>;
}
