create table if not exists public.contract_events (
  id bigint generated by default as identity primary key,
  contract_id text not null,
  event_id text not null,
  ledger bigint not null,
  tx_hash text,
  name text not null,
  topics jsonb not null default '[]'::jsonb,
  data jsonb,
  ledger_closed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (contract_id, event_id)
);

create index if not exists contract_events_ledger_idx on public.contract_events (ledger desc);
create index if not exists contract_events_name_idx on public.contract_events (name, ledger desc);

alter table public.contract_events enable row level security;

-- The indexer uses the server-only service_role key. No browser role gets access.
revoke all on table public.contract_events from anon, authenticated;
grant all on table public.contract_events to service_role;
